\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{LnxClase}[2025/03/18 Plantilla personalizada]

 
\LoadClass[a4paper]{article}

 
\RequirePackage[utf8]{inputenc}
\RequirePackage[spanish]{babel}
\RequirePackage{amsmath, amssymb, physics}
\RequirePackage{tikz}
\RequirePackage{geometry}
\RequirePackage{Lnx}  
 
 %size personalizado 
\geometry{papersize={21cm,32cm}, top=1in, left=1in, right=1in, bottom=1.5in, includefoot}

\endinput